import { FaArrowRight } from 'react-icons/fa';
import { FaHtml5 } from 'react-icons/fa';
import { FaCss3 } from 'react-icons/fa';
import { IoLogoJavascript } from 'react-icons/io5';
import { SiNextra, SiTypescript } from 'react-icons/si';
import { FaReact } from 'react-icons/fa';
import { TbBrandRedux } from 'react-icons/tb';
import { AiOutlineAppstoreAdd } from 'react-icons/ai';
import { IoIosWarning } from 'react-icons/io';
import { FaInfoCircle } from 'react-icons/fa';
import { BsLightbulbFill } from 'react-icons/bs';
import { MdDangerous } from 'react-icons/md';
import { AiFillTags } from 'react-icons/ai';
import { IoIosSettings } from 'react-icons/io';

export const Default = () => <FaArrowRight />;
export const WarnCallout = () => <IoIosWarning />;
export const InfoCallout = () => <FaInfoCircle />;
export const DangerCallout = () => <MdDangerous />;
export const DefaultCallout = () => <BsLightbulbFill />;
export const All = () => <AiOutlineAppstoreAdd />;
export const Archives = () => <AiFillTags />;
export const Html = () => <FaHtml5 />;
export const Css = () => <FaCss3 />;
export const Js = () => <IoLogoJavascript />;
export const Ts = () => <SiTypescript />;
export const React = () => <FaReact />;
export const Redux = () => <TbBrandRedux />;
export const Dev = () => <SiNextra />;
